services:
  # --- Prometheus ---
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - /mnt/hdd/prometheus:/prometheus
    restart: unless-stopped

  mikrotik-exporter:
    image: nshttpd/mikrotik-exporter:latest
    container_name: mikrotik-exporter
    restart: unless-stopped
    ports:
      - "9436:9436"
    environment:
      MIKROTIK_DEVICE_ADDRESS: "192.168.1.1"
      MIKROTIK_DEVICE_USER: "admin"
      MIKROTIK_DEVICE_PASSWORD: "admin"
      MIKROTIK_DEVICE_PORT: "8728"
      MIKROTIK_DEVICE_NAME: "mikrotik"
  influxdb2:
    image: influxdb:2
    ports:
      - 8086:8086
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME_FILE: /run/secrets/influxdb2-admin-username
      DOCKER_INFLUXDB_INIT_PASSWORD_FILE: /run/secrets/influxdb2-admin-password
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN_FILE: /run/secrets/influxdb2-admin-token
      DOCKER_INFLUXDB_INIT_ORG: docs
      DOCKER_INFLUXDB_INIT_BUCKET: home
    secrets:
      - influxdb2-admin-username
      - influxdb2-admin-password
      - influxdb2-admin-token
    volumes:
      - /mnt/hdd/influxdb2-data:/var/lib/influxdb2
      - /mnt/hdd/influxdb2-config:/etc/influxdb2
    restart: unless-stopped

  # --- Grafana ---
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "2000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - /mnt/hdd/grafana:/var/lib/grafana
    depends_on:
      - prometheus
    restart: unless-stopped

secrets:
  influxdb2-admin-username:
    file: ./.env.user
  influxdb2-admin-password:
    file: ./.env.password
  influxdb2-admin-token:
    file: ./.env.admin-token