global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # --- Prometheus itself ---
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  # --- Proxmox Exporter ---
  - job_name: 'proxmox'
    static_configs:
      - targets: ['proxmox-exporter:9221']

  # --- MikroTik Exporter ---
  - job_name: 'mikrotik'
    static_configs:
      - targets: ['mikrotik-exporter:9436']
