services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /mnt/hdd/tramission:/config
      - /mnt/hdd/media:/downloads
      - /mnt/hdd/transmission/watch:/watch 
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
    networks:
      media-server:
        ipv4_address: 10.5.0.5
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /mnt/hdd/sonarr:/config
      - /mnt/hdd/media:/tv
      - /mnt/hdd/media/complete/tv-sonarr:/downloads/complete/tv-sonarr
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      media-server:
        ipv4_address: 10.5.0.6
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /mnt/hdd/radarr:/config
      - /mnt/hdd/media:/movies
      - /mnt/hdd/media/complete/radarr:/downloads/complete/movies-radarr
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      media-server:
        ipv4_address: 10.5.0.7
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /mnt/hdd/overseer:/config
    ports:
      - 5055:5055
    restart: unless-stopped
    networks:
      media-server:
        ipv4_address: 10.5.0.8
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /mnt/hdd/powlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    networks:
      media-server:
        ipv4_address: 10.5.0.9
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    ports:
      - 8096:8096/tcp
      - 7359:7359/udp
    volumes:
      - /mnt/hdd/jellyfin/config:/config
      - /mnt/hdd/jellyfin/cache:/cache
      - type: bind
        source: /mnt/hdd/media
        target: /media
        read_only: true
      # Optional - extra fonts to be used during transcoding with subtitle burn-in
      - type: bind
        source: /mnt/hdd/fonts
        target: /usr/local/share/fonts/custom
        read_only: true
    restart: 'unless-stopped'
    # Optional - alternative address used for autodiscovery
    environment:
      - JELLYFIN_PublishedServerUrl=http://tv.gyurus.hu
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    extra_hosts:
      - 'host.docker.internal:host-gateway'
  jellyfin-auto-collections:
    image: ghcr.io/ghomashudson/jellyfin-auto-collections:latest
    container_name: jellyfin-auto-collections
    environment:
      - CRONTAB=10 * * * *
      - TZ=Europe/Budapest
      - JELLYFIN_SERVER_URL=http://jellyfin:8096
      - JELLYFIN_API_KEY=ef6f7f4f7d5c478dae00828076283ab2
      - JELLYFIN_USER_ID=b0fd141a59634beb9fd651db4abc350f
    volumes:
      - /mnt/hdd/jellyfin-auto-collections/config:/app/config
  plex:
    image: plexinc/pms-docker:latest
    privileged: true
    container_name: plex
    network_mode: host
    devices:
    - /dev/bus/usb:/dev/bus/usb
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Budapest
      - ADVERTISE_IP=https://stream.gyurus.hu
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/hdd/plexmediaserver:/config
      - /mnt/hdd/media:/mnt/tv
      - /mnt/hdd/media:/mnt/movies
    restart: unless-stopped
networks:
  media-server:
    name: media-server
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1