name: Generate Mermaid Diagrams

on:
  push:
    paths:
      - /diagrams/immich.mmd
      - /diagrams/infra.mmd
      - /diagrams/torrent.mmd
      - .github/workflows/mermaid.yml
  workflow_dispatch:

jobs:
  generate-diagram:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install mermaid-cli
        run: npm install -g @mermaid-js/mermaid-cli

      - name: Generate PNG from Mermaid file (infra)
        run: mmdc -i diagrams/infra.mmd -o diagrams/infra.png --puppeteerConfigFile ./diagrams/puppeteer-config.json --scale 2

      - name: Generate PNG from Mermaid file (torrent)
        run: mmdc -i diagrams/torrent.mmd -o diagrams/torrent.png --puppeteerConfigFile ./diagrams/puppeteer-config.json --scale 2

      - name: Generate PNG from Mermaid file (immich)
        run: mmdc -i diagrams/immich.mmd -o diagrams/immich.png --puppeteerConfigFile ./diagrams/puppeteer-config.json --scale 2

      - name: Commit diagram image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add ./diagrams/immich.png ./diagrams/infra.png ./diagrams/torrent.png
          git commit -m "Auto-generated Mermaid diagram image for push ${{ github.sha }}" || echo "No changes to commit"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:${{ github.ref }}
